build:
  - platform: src
  - platform: linux
    arch:
      - amd64
      - arm64
  - platform: darwin
    arch:
      - "386"
      - amd64
  - platform: windows
    arch:
      - "386"
      - amd64
include:
  - README.md
  - LICENSE
outputDir: "$GOPATH/bin"
